import React, { useMemo, useState } from 'react';
import { FiChevronDown, FiDownload, FiHelpCircle, FiRefreshCw, FiCalendar, FiX } from 'react-icons/fi';
import { REMINDER_CHOICES, downloadIcs } from '../lib/calendarLinks';
import './CalendarSyncPanel.css';

/**
 * Bulk calendar sync for the calendar of activities.
 *
 * One .ics file holding every selected activity, which Google Calendar, Apple
 * Calendar and Outlook all import. It is a snapshot rather than a live
 * subscription feed — a subscribe-by-URL feed has to be generated by a server,
 * and this site is static — so the panel says so plainly and makes re-importing
 * a single click. Re-importing does not create duplicates: each event carries a
 * stable UID, so calendars update the existing entry instead of adding another.
 */
const SCOPES = [
  { id: 'upcoming', label: 'Upcoming only', hint: 'Everything from today onwards' },
  { id: 'all', label: 'All activities', hint: 'Including events that have passed' }
];

const CalendarSyncPanel = ({ events = [] }) => {
  // Collapsed by default: this sits below the calendar itself, and most visits
  // are to read the schedule rather than export it.
  const [open, setOpen] = useState(false);
  const [scope, setScope] = useState('upcoming');
  const [reminder, setReminder] = useState(24 * 60);
  const [showHelp, setShowHelp] = useState(false);
  const [lastExport, setLastExport] = useState('');

  const selected = useMemo(() => {
    const startOfToday = new Date();
    startOfToday.setHours(0, 0, 0, 0);

    return events
      .filter((event) => event?.date)
      .filter((event) => scope === 'all' || new Date(event.date) >= startOfToday)
      .sort((a, b) => new Date(a.date) - new Date(b.date));
  }, [events, scope]);

  const handleDownload = () => {
    if (!selected.length) return;
    downloadIcs(selected, {
      reminderMinutes: reminder,
      calendarName: 'PSU-UCC SSC Activities',
      fileName: 'psu-ucc-ssc-activities.ics'
    });
    setLastExport(new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }));
  };

  if (!open) {
    return (
      <div className="calendar-sync-collapsed">
        <button type="button" className="sync-open-btn" onClick={() => setOpen(true)}>
          <span className="sync-icon"><FiCalendar /></span>
          <span className="sync-open-text">
            <strong>Sync to your own calendar</strong>
            <small>
              Add these activities to Google Calendar, Apple Calendar or Outlook, with reminders
            </small>
          </span>
          <FiChevronDown />
        </button>
      </div>
    );
  }

  return (
    <div className="calendar-sync-panel">
      <div className="sync-head">
        <span className="sync-icon"><FiCalendar /></span>
        <div className="sync-head-text">
          <h3>Sync to your own calendar</h3>
          <p>
            Put the SSC calendar of activities into Google Calendar, Apple Calendar or Outlook,
            with reminders, so you get notified without opening this site.
          </p>
        </div>
        <button
          type="button"
          className="sync-close-btn"
          onClick={() => setOpen(false)}
          aria-label="Hide calendar sync"
        >
          <FiX />
        </button>
      </div>

      <div className="sync-controls">
        <div className="sync-field">
          <label htmlFor="sync-scope">Include</label>
          <select id="sync-scope" value={scope} onChange={(e) => setScope(e.target.value)}>
            {SCOPES.map((option) => (
              <option key={option.id} value={option.id}>{option.label}</option>
            ))}
          </select>
          <small>{SCOPES.find((option) => option.id === scope)?.hint}</small>
        </div>

        <div className="sync-field">
          <label htmlFor="sync-reminder">Reminder</label>
          <select id="sync-reminder" value={reminder} onChange={(e) => setReminder(Number(e.target.value))}>
            {REMINDER_CHOICES.map((choice) => (
              <option key={choice.value} value={choice.value}>{choice.label}</option>
            ))}
          </select>
          <small>Set on every imported activity</small>
        </div>

        <button
          type="button"
          className="sync-download-btn"
          onClick={handleDownload}
          disabled={!selected.length}
        >
          <FiDownload />
          {selected.length
            ? `Download ${selected.length} ${selected.length === 1 ? 'activity' : 'activities'}`
            : 'Nothing to sync yet'}
        </button>
      </div>

      {!!lastExport && (
        <p className="sync-confirmation">
          <FiRefreshCw /> Exported at {lastExport}. Open the downloaded file to add the
          activities — come back and download again whenever the calendar changes.
        </p>
      )}

      <button type="button" className="sync-help-toggle" onClick={() => setShowHelp(!showHelp)}>
        <FiHelpCircle /> How do I import this?
        <FiChevronDown className={showHelp ? 'rotated' : ''} />
      </button>

      {showHelp && (
        <div className="sync-help">
          <div className="sync-help-item">
            <h4>Google Calendar</h4>
            <p>
              On a computer, open <b>calendar.google.com</b> → gear icon → <b>Settings</b> →
              <b> Import &amp; export</b> → choose the downloaded file → <b>Import</b>. On phones,
              Google Calendar cannot import files, so use the <b>Add</b> button on an individual
              activity instead.
            </p>
          </div>
          <div className="sync-help-item">
            <h4>Apple Calendar (iPhone, iPad, Mac)</h4>
            <p>
              Just open the downloaded file. iOS shows an <b>Add All</b> button; on a Mac it opens
              in Calendar and asks which calendar to add them to.
            </p>
          </div>
          <div className="sync-help-item">
            <h4>Outlook</h4>
            <p>
              Outlook desktop opens the file directly. On the web, go to <b>Add calendar</b> →
              <b> Upload from file</b> and pick the downloaded file.
            </p>
          </div>
          <p className="sync-help-note">
            This file is a snapshot of the calendar as it is right now, not a live feed. Downloading
            it again after the SSC adds or changes an activity updates the entries you already
            imported rather than duplicating them.
          </p>
        </div>
      )}
    </div>
  );
};

export default CalendarSyncPanel;
